/*************************************************************************\
    Copyright (c) 2015 Corporation for National Research Initiatives;
                        All rights reserved.
     The CNRI open source license for this software is available at
                  http://hdl.handle.net/20.1000/106
\*************************************************************************/

(function(){
"use strict";

var window = window || self;

function AutoGeneratedField(textInput, editor) {
    
    var self = this;
    
    function constructor() {
        var fieldName = JsonUtil.getDeepProperty(editor.schema, Constants.REPOSITORY_SCHEMA_KEYWORD, 'type', 'autoGeneratedField');
        textInput.prop("disabled", true);
        if (textInput.val() === "") {
            textInput.attr("placeholder", "Auto generated field " + fieldName);
        }
    }
    
    constructor();
}

window.AutoGeneratedField = AutoGeneratedField;

})();